/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { BodyImportBankStatementApiImportPostMode } from "./bodyImportBankStatementApiImportPostMode";

export interface BodyImportBankStatementApiImportPost {
  file: Blob;
  /** Тип банку: 'wise', 'p24', 'revolut', 'pumb', 'erste', 'raiffeisen' */
  mode: BodyImportBankStatementApiImportPostMode;
  /** Дія: 'show' для перегляду або 'import' для імпорту */
  action?: string;
}
