/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Тип банку: 'wise', 'p24', 'revolut'
 */
export type BodyImportBankStatementApiImportPostMode =
  (typeof BodyImportBankStatementApiImportPostMode)[keyof typeof BodyImportBankStatementApiImportPostMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BodyImportBankStatementApiImportPostMode = {
  wise: "wise",
  p24: "p24",
  revolut: "revolut",
} as const;
