/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryUpdateName } from "./categoryUpdateName";
import type { CategoryUpdateParentId } from "./categoryUpdateParentId";

export interface CategoryUpdate {
  name?: CategoryUpdateName;
  parent_id?: CategoryUpdateParentId;
}
