/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryResponseId } from "./categoryResponseId";
import type { CategoryResponseName } from "./categoryResponseName";
import type { CategoryResponseParentId } from "./categoryResponseParentId";
import type { CategoryResponseOrd } from "./categoryResponseOrd";
import type { CategoryResponseIsVisible } from "./categoryResponseIsVisible";
import type { CategoryResponseUserId } from "./categoryResponseUserId";
import type { CategoryResponseGroupId } from "./categoryResponseGroupId";
import type { CategoryResponseIsFuel } from "./categoryResponseIsFuel";

/**
 * Схема для відповіді з даними категорії
 */
export interface CategoryResponse {
  id?: CategoryResponseId;
  name?: CategoryResponseName;
  parent_id?: CategoryResponseParentId;
  ord?: CategoryResponseOrd;
  is_visible?: CategoryResponseIsVisible;
  user_id?: CategoryResponseUserId;
  group_id?: CategoryResponseGroupId;
  is_fuel?: CategoryResponseIsFuel;
}
