/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Дані для групового створення показників
 */
export type CreateBatchReadingsApiUtilitiesReadingsBatchPostBody = {
  [key: string]: unknown;
};
