/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */

export type GetPaymentsApiPaymentsGetParams = {
  /**
   * Рік для фільтрації
   */
  year?: string | null;
  /**
   * Місяць для фільтрації
   */
  month?: string | null;
  /**
   * Пошуковий запит
   */
  q?: string | null;
  /**
   * ID категорії для фільтрації. Спеціальне значення '_' для останніх платежів
   */
  category_id?: string | null;
  /**
   * Валюта для відображення сум
   */
  currency?: string | null;
  /**
   * ID користувача групи
   */
  group_user_id?: string | null;
};
