/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { GroupUserResponseId } from "./groupUserResponseId";
import type { GroupUserResponseLogin } from "./groupUserResponseLogin";
import type { GroupUserResponseFullname } from "./groupUserResponseFullname";
import type { GroupUserResponsePhone } from "./groupUserResponsePhone";
import type { GroupUserResponseEmail } from "./groupUserResponseEmail";
import type { GroupUserResponseCreated } from "./groupUserResponseCreated";
import type { GroupUserResponseIsAdmin } from "./groupUserResponseIsAdmin";
import type { GroupUserResponseRole } from "./groupUserResponseRole";
import type { GroupUserResponseRelationType } from "./groupUserResponseRelationType";

/**
 * Схема для відповіді з даними користувача в групі
 */
export interface GroupUserResponse {
  id?: GroupUserResponseId;
  login?: GroupUserResponseLogin;
  fullname?: GroupUserResponseFullname;
  phone?: GroupUserResponsePhone;
  email?: GroupUserResponseEmail;
  created?: GroupUserResponseCreated;
  is_admin?: GroupUserResponseIsAdmin;
  role?: GroupUserResponseRole;
  relation_type?: GroupUserResponseRelationType;
}
