/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceGroup } from "./serviceGroup";
import type { ServiceWithReadings } from "./serviceWithReadings";

/**
 * Відповідь для згрупованих показників
 */
export interface GroupedReadingsResponse {
  address_id: number;
  period: string;
  service_groups: ServiceGroup[];
  services: ServiceWithReadings[];
}
