/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { GroupResponseId } from "./groupResponseId";
import type { GroupResponseName } from "./groupResponseName";
import type { GroupResponseDescription } from "./groupResponseDescription";
import type { GroupResponseOwnerId } from "./groupResponseOwnerId";
import type { GroupResponseCreated } from "./groupResponseCreated";

/**
 * Схема для відповіді з даними групи
 */
export interface GroupResponse {
  id?: GroupResponseId;
  name?: GroupResponseName;
  description?: GroupResponseDescription;
  owner_id?: GroupResponseOwnerId;
  created?: GroupResponseCreated;
}
