/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { GroupUserUpdateRole } from "./groupUserUpdateRole";
import type { GroupUserUpdateRelationType } from "./groupUserUpdateRelationType";

/**
 * Схема для оновлення інформації про користувача в групі
 */
export interface GroupUserUpdate {
  role?: GroupUserUpdateRole;
  relation_type?: GroupUserUpdateRelationType;
}
