/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { GroupInvitationResponseId } from "./groupInvitationResponseId";
import type { GroupInvitationResponseGroupId } from "./groupInvitationResponseGroupId";
import type { GroupInvitationResponseCreatedBy } from "./groupInvitationResponseCreatedBy";
import type { GroupInvitationResponseInvitationCode } from "./groupInvitationResponseInvitationCode";
import type { GroupInvitationResponseEmail } from "./groupInvitationResponseEmail";
import type { GroupInvitationResponseIsActive } from "./groupInvitationResponseIsActive";
import type { GroupInvitationResponseCreated } from "./groupInvitationResponseCreated";
import type { GroupInvitationResponseExpires } from "./groupInvitationResponseExpires";
import type { GroupInvitationResponseGroup } from "./groupInvitationResponseGroup";
import type { GroupInvitationResponseCreator } from "./groupInvitationResponseCreator";

/**
 * Схема для відповіді з даними запрошення в групу
 */
export interface GroupInvitationResponse {
  id?: GroupInvitationResponseId;
  group_id?: GroupInvitationResponseGroupId;
  created_by?: GroupInvitationResponseCreatedBy;
  invitation_code?: GroupInvitationResponseInvitationCode;
  email?: GroupInvitationResponseEmail;
  is_active?: GroupInvitationResponseIsActive;
  created?: GroupInvitationResponseCreated;
  expires?: GroupInvitationResponseExpires;
  group?: GroupInvitationResponseGroup;
  creator?: GroupInvitationResponseCreator;
}
