/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Роль, яка буде призначена користувачу
 */
export type GroupInvitationRole = string | null;
