/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { GroupUpdateName } from "./groupUpdateName";
import type { GroupUpdateDescription } from "./groupUpdateDescription";

export interface GroupUpdate {
  /** Назва групи */
  name?: GroupUpdateName;
  /** Опис групи */
  description?: GroupUpdateDescription;
}
