/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { GroupInvitationRole } from "./groupInvitationRole";

export interface GroupInvitation {
  /** Email користувача для запрошення */
  email: string;
  /** Роль, яка буде призначена користувачу */
  role?: GroupInvitationRole;
}
