/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { GroupedReadingItemId } from "./groupedReadingItemId";
import type { GroupedReadingItemServiceId } from "./groupedReadingItemServiceId";
import type { GroupedReadingItemTariffName } from "./groupedReadingItemTariffName";
import type { GroupedReadingItemTariffType } from "./groupedReadingItemTariffType";
import type { GroupedReadingItemCurrentReading } from "./groupedReadingItemCurrentReading";
import type { GroupedReadingItemPreviousReading } from "./groupedReadingItemPreviousReading";
import type { GroupedReadingItemConsumption } from "./groupedReadingItemConsumption";
import type { GroupedReadingItemAmount } from "./groupedReadingItemAmount";
import type { GroupedReadingItemTariff } from "./groupedReadingItemTariff";
import type { GroupedReadingItemIsPaid } from "./groupedReadingItemIsPaid";
import type { GroupedReadingItemPeriod } from "./groupedReadingItemPeriod";
import type { GroupedReadingItemReadingDate } from "./groupedReadingItemReadingDate";

/**
 * Елемент згрупованого показника
 */
export interface GroupedReadingItem {
  id?: GroupedReadingItemId;
  service_id?: GroupedReadingItemServiceId;
  service_name: string;
  tariff_name?: GroupedReadingItemTariffName;
  tariff_type?: GroupedReadingItemTariffType;
  current_reading?: GroupedReadingItemCurrentReading;
  previous_reading?: GroupedReadingItemPreviousReading;
  consumption?: GroupedReadingItemConsumption;
  amount?: GroupedReadingItemAmount;
  tariff?: GroupedReadingItemTariff;
  is_paid?: GroupedReadingItemIsPaid;
  period?: GroupedReadingItemPeriod;
  reading_date?: GroupedReadingItemReadingDate;
}
