/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { InvitationAcceptAcceptData } from "./invitationAcceptAcceptData";

export interface InvitationAccept {
  /** Додаткові дані для прийняття запрошення */
  accept_data?: InvitationAcceptAcceptData;
}
