/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { InvitationIgnoreIgnoreReason } from "./invitationIgnoreIgnoreReason";

export interface InvitationIgnore {
  /** Причина ігнорування запрошення */
  ignore_reason?: InvitationIgnoreIgnoreReason;
}
