/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Режим обробки платежів
 */
export type MonoPaymentProcessRequestMode = string | null;
