/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Кінцева дата (формат: YYYY-MM-DD)
 */
export type MonoPaymentProcessRequestToDate = string | null;
