/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { MonoUserUpdateToken } from "./monoUserUpdateToken";
import type { MonoUserUpdateName } from "./monoUserUpdateName";
import type { MonoUserUpdateStatus } from "./monoUserUpdateStatus";

export interface MonoUserUpdate {
  /** Токен mono API */
  token?: MonoUserUpdateToken;
  /** Назва для користувача */
  name?: MonoUserUpdateName;
  /** Статус активності */
  status?: MonoUserUpdateStatus;
}
