/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { PaymentUpdateAmount } from "./paymentUpdateAmount";
import type { PaymentUpdateCurrencyAmount } from "./paymentUpdateCurrencyAmount";
import type { PaymentUpdateDescription } from "./paymentUpdateDescription";
import type { PaymentUpdateMydesc } from "./paymentUpdateMydesc";
import type { PaymentUpdateCategoryId } from "./paymentUpdateCategoryId";
import type { PaymentUpdateRdate } from "./paymentUpdateRdate";
import type { PaymentUpdateSource } from "./paymentUpdateSource";
import type { PaymentUpdateRefuelData } from "./paymentUpdateRefuelData";
import type { PaymentUpdateAmountOriginal } from "./paymentUpdateAmountOriginal";
import type { PaymentUpdateCurrencyOriginal } from "./paymentUpdateCurrencyOriginal";
import type { PaymentUpdateExchangeRate } from "./paymentUpdateExchangeRate";

export interface PaymentUpdate {
  /** Сума платежу */
  amount?: PaymentUpdateAmount;
  /** Сума платежу в оригінальній валюті */
  currency_amount?: PaymentUpdateCurrencyAmount;
  /** Опис платежу */
  description?: PaymentUpdateDescription;
  /** Додатковий опис (автоматично генерується для заправки) */
  mydesc?: PaymentUpdateMydesc;
  /** ID категорії */
  category_id?: PaymentUpdateCategoryId;
  /** Валюта платежу */
  currency?: string;
  /** Дата платежу */
  rdate?: PaymentUpdateRdate;
  /** Джерело платежу (mono, p24, revolut, wise, webapp) */
  source?: PaymentUpdateSource;
  /** Дані про заправку (якщо це заправка) */
  refuel_data?: PaymentUpdateRefuelData;
  /** Original amount in transaction currency */
  amount_original?: PaymentUpdateAmountOriginal;
  /** Original transaction currency */
  currency_original?: PaymentUpdateCurrencyOriginal;
  /** Exchange rate at transaction time */
  exchange_rate?: PaymentUpdateExchangeRate;
}
