/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */

export interface PaymentCategoryUpdate {
  /** Список ID платежів */
  payment_ids: number[];
  /** ID нової категорії */
  category_id: number;
}
