/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { PaymentCreateAmount } from "./paymentCreateAmount";
import type { PaymentCreateCurrencyAmount } from "./paymentCreateCurrencyAmount";
import type { PaymentCreateDescription } from "./paymentCreateDescription";
import type { PaymentCreateMydesc } from "./paymentCreateMydesc";
import type { PaymentCreateCategoryId } from "./paymentCreateCategoryId";
import type { PaymentCreateRdate } from "./paymentCreateRdate";
import type { PaymentCreateSource } from "./paymentCreateSource";
import type { PaymentCreateRefuelData } from "./paymentCreateRefuelData";
import type { PaymentCreateAmountOriginal } from "./paymentCreateAmountOriginal";
import type { PaymentCreateCurrencyOriginal } from "./paymentCreateCurrencyOriginal";
import type { PaymentCreateExchangeRate } from "./paymentCreateExchangeRate";
import type { PaymentCreateBankPaymentId } from "./paymentCreateBankPaymentId";
import type { PaymentCreateUserId } from "./paymentCreateUserId";

export interface PaymentCreate {
  /** Сума платежу */
  amount?: PaymentCreateAmount;
  /** Сума платежу в оригінальній валюті */
  currency_amount?: PaymentCreateCurrencyAmount;
  /** Опис платежу */
  description?: PaymentCreateDescription;
  /** Додатковий опис (автоматично генерується для заправки) */
  mydesc?: PaymentCreateMydesc;
  /** ID категорії */
  category_id?: PaymentCreateCategoryId;
  /** Валюта платежу */
  currency?: string;
  /** Дата платежу */
  rdate?: PaymentCreateRdate;
  /** Джерело платежу (mono, p24, revolut, wise, webapp) */
  source?: PaymentCreateSource;
  /** Дані про заправку (якщо це заправка) */
  refuel_data?: PaymentCreateRefuelData;
  /** Original amount in transaction currency */
  amount_original?: PaymentCreateAmountOriginal;
  /** Original transaction currency */
  currency_original?: PaymentCreateCurrencyOriginal;
  /** Exchange rate at transaction time */
  exchange_rate?: PaymentCreateExchangeRate;
  /** Унікальний ID платежу (генерується автоматично) */
  bank_payment_id?: PaymentCreateBankPaymentId;
  /** ID користувача (встановлюється автоматично) */
  user_id?: PaymentCreateUserId;
}
