/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Джерело платежу (mono, p24, revolut, wise, webapp)
 */
export type PaymentCreateSource = string | null;
