/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */

export type PaymentByMonthsApiPaymentsYearMonthsGetParams = {
  /**
   * ID користувача Monobank
   */
  mono_user_id?: string | null;
  /**
   * Валюта
   */
  currency?: string;
};
