/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Original amount in transaction currency
 */
export type PaymentUpdateAmountOriginal = number | null;
