/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */

export interface PaymentBulkDelete {
  /** Список ID платежів для видалення */
  payment_ids: number[];
}
