/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */

export type PaymentsForPeriodApiPaymentsPeriodGetParams = {
  /**
   * Рік для фільтрації
   */
  year?: string;
  /**
   * Місяць для фільтрації
   */
  month?: string;
  /**
   * ID користувача Monobank
   */
  mono_user_id?: string | null;
  /**
   * Валюта
   */
  currency?: string;
  /**
   * ID користувача групи
   */
  group_user_id?: string | null;
};
