/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { RefuelData } from "./refuelData";

/**
 * Дані про заправку (якщо це заправка)
 */
export type PaymentCreateRefuelData = RefuelData | null;
