/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { RefuelDataKm } from "./refuelDataKm";
import type { RefuelDataLitres } from "./refuelDataLitres";
import type { RefuelDataPriceVal } from "./refuelDataPriceVal";
import type { RefuelDataStationName } from "./refuelDataStationName";

export interface RefuelData {
  /** Пробіг у кілометрах */
  km?: RefuelDataKm;
  /** Кількість літрів палива */
  litres?: RefuelDataLitres;
  /** Ціна за літр палива (в EUR) */
  price_val?: RefuelDataPriceVal;
  /** Назва заправки */
  station_name?: RefuelDataStationName;
}
