/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceInGroup } from "./serviceInGroup";
import type { GroupedReadingItem } from "./groupedReadingItem";

/**
 * Група служб
 */
export interface ServiceGroup {
  group_name: string;
  services: ServiceInGroup[];
  readings: GroupedReadingItem[];
  total_amount: number;
  has_shared_meter: boolean;
}
