/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { GroupedReadingItem } from "./groupedReadingItem";

/**
 * Служба з показниками
 */
export interface ServiceWithReadings {
  service_id: number;
  service_name: string;
  unit: string;
  has_shared_meter: boolean;
  readings: GroupedReadingItem[];
  total_amount: number;
}
