/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Служба в групі
 */
export interface ServiceInGroup {
  id: number;
  name: string;
  unit: string;
  has_shared_meter: boolean;
}
