/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponseId } from "./userResponseId";
import type { UserResponseLogin } from "./userResponseLogin";
import type { UserResponseFullname } from "./userResponseFullname";
import type { UserResponsePhone } from "./userResponsePhone";
import type { UserResponseEmail } from "./userResponseEmail";
import type { UserResponseCreated } from "./userResponseCreated";
import type { UserResponseIsAdmin } from "./userResponseIsAdmin";

/**
 * Схема для відповіді з даними користувача
 */
export interface UserResponse {
  id?: UserResponseId;
  login?: UserResponseLogin;
  fullname?: UserResponseFullname;
  phone?: UserResponsePhone;
  email?: UserResponseEmail;
  created?: UserResponseCreated;
  is_admin?: UserResponseIsAdmin;
}
