/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */

export interface UserCreate {
  login: string;
  password: string;
  fullname?: string;
  phone?: string;
  email?: string;
}
