/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { UtilityAddressCreateDescription } from "./utilityAddressCreateDescription";
import type { UtilityAddressCreateIsActive } from "./utilityAddressCreateIsActive";
import type { UtilityAddressCreateSource } from "./utilityAddressCreateSource";

/**
 * Схема для створення адреси комунальних служб
 */
export interface UtilityAddressCreate {
  name: string;
  address: string;
  description?: UtilityAddressCreateDescription;
  is_active?: UtilityAddressCreateIsActive;
  source?: UtilityAddressCreateSource;
}
