/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { UtilityServiceUpdateAddressId } from "./utilityServiceUpdateAddressId";
import type { UtilityServiceUpdateName } from "./utilityServiceUpdateName";
import type { UtilityServiceUpdateDescription } from "./utilityServiceUpdateDescription";
import type { UtilityServiceUpdateUnit } from "./utilityServiceUpdateUnit";
import type { UtilityServiceUpdateMeterNumber } from "./utilityServiceUpdateMeterNumber";
import type { UtilityServiceUpdateIsActive } from "./utilityServiceUpdateIsActive";
import type { UtilityServiceUpdateHasSharedMeter } from "./utilityServiceUpdateHasSharedMeter";
import type { UtilityServiceUpdateServiceGroup } from "./utilityServiceUpdateServiceGroup";

/**
 * Схема для оновлення комунальної служби
 */
export interface UtilityServiceUpdate {
  address_id?: UtilityServiceUpdateAddressId;
  name?: UtilityServiceUpdateName;
  description?: UtilityServiceUpdateDescription;
  unit?: UtilityServiceUpdateUnit;
  meter_number?: UtilityServiceUpdateMeterNumber;
  is_active?: UtilityServiceUpdateIsActive;
  has_shared_meter?: UtilityServiceUpdateHasSharedMeter;
  service_group?: UtilityServiceUpdateServiceGroup;
}
