/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { UtilityTariffUpdateName } from "./utilityTariffUpdateName";
import type { UtilityTariffUpdateRate } from "./utilityTariffUpdateRate";
import type { UtilityTariffUpdateSubscriptionFee } from "./utilityTariffUpdateSubscriptionFee";
import type { UtilityTariffUpdateCurrency } from "./utilityTariffUpdateCurrency";
import type { UtilityTariffUpdateValidFrom } from "./utilityTariffUpdateValidFrom";
import type { UtilityTariffUpdateValidTo } from "./utilityTariffUpdateValidTo";
import type { UtilityTariffUpdateIsActive } from "./utilityTariffUpdateIsActive";
import type { UtilityTariffUpdateTariffType } from "./utilityTariffUpdateTariffType";
import type { UtilityTariffUpdateGroupCode } from "./utilityTariffUpdateGroupCode";
import type { UtilityTariffUpdateCalculationMethod } from "./utilityTariffUpdateCalculationMethod";
import type { UtilityTariffUpdatePercentageOf } from "./utilityTariffUpdatePercentageOf";

/**
 * Схема для оновлення тарифу
 */
export interface UtilityTariffUpdate {
  name?: UtilityTariffUpdateName;
  rate?: UtilityTariffUpdateRate;
  subscription_fee?: UtilityTariffUpdateSubscriptionFee;
  currency?: UtilityTariffUpdateCurrency;
  valid_from?: UtilityTariffUpdateValidFrom;
  valid_to?: UtilityTariffUpdateValidTo;
  is_active?: UtilityTariffUpdateIsActive;
  tariff_type?: UtilityTariffUpdateTariffType;
  group_code?: UtilityTariffUpdateGroupCode;
  calculation_method?: UtilityTariffUpdateCalculationMethod;
  percentage_of?: UtilityTariffUpdatePercentageOf;
}
