/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { UtilityReadingResponseId } from "./utilityReadingResponseId";
import type { UtilityReadingResponseUserId } from "./utilityReadingResponseUserId";
import type { UtilityReadingResponseAddressId } from "./utilityReadingResponseAddressId";
import type { UtilityReadingResponseServiceId } from "./utilityReadingResponseServiceId";
import type { UtilityReadingResponsePeriod } from "./utilityReadingResponsePeriod";
import type { UtilityReadingResponseCurrentReading } from "./utilityReadingResponseCurrentReading";
import type { UtilityReadingResponsePreviousReading } from "./utilityReadingResponsePreviousReading";
import type { UtilityReadingResponseConsumption } from "./utilityReadingResponseConsumption";
import type { UtilityReadingResponseTariffId } from "./utilityReadingResponseTariffId";
import type { UtilityReadingResponseAmount } from "./utilityReadingResponseAmount";
import type { UtilityReadingResponseReadingDate } from "./utilityReadingResponseReadingDate";
import type { UtilityReadingResponseIsPaid } from "./utilityReadingResponseIsPaid";
import type { UtilityReadingResponseNotes } from "./utilityReadingResponseNotes";
import type { UtilityReadingResponseCreated } from "./utilityReadingResponseCreated";
import type { UtilityReadingResponseUpdated } from "./utilityReadingResponseUpdated";
import type { UtilityReadingResponseAddress } from "./utilityReadingResponseAddress";
import type { UtilityReadingResponseService } from "./utilityReadingResponseService";
import type { UtilityReadingResponseTariff } from "./utilityReadingResponseTariff";
import type { UtilityReadingResponseCalculationDetails } from "./utilityReadingResponseCalculationDetails";
import type { UtilityReadingResponseReadingType } from "./utilityReadingResponseReadingType";

/**
 * Схема для відповіді з даними показників комунальної служби
 */
export interface UtilityReadingResponse {
  id?: UtilityReadingResponseId;
  user_id?: UtilityReadingResponseUserId;
  address_id?: UtilityReadingResponseAddressId;
  service_id?: UtilityReadingResponseServiceId;
  period?: UtilityReadingResponsePeriod;
  current_reading?: UtilityReadingResponseCurrentReading;
  previous_reading?: UtilityReadingResponsePreviousReading;
  consumption?: UtilityReadingResponseConsumption;
  tariff_id?: UtilityReadingResponseTariffId;
  amount?: UtilityReadingResponseAmount;
  reading_date?: UtilityReadingResponseReadingDate;
  is_paid?: UtilityReadingResponseIsPaid;
  notes?: UtilityReadingResponseNotes;
  created?: UtilityReadingResponseCreated;
  updated?: UtilityReadingResponseUpdated;
  address?: UtilityReadingResponseAddress;
  service?: UtilityReadingResponseService;
  tariff?: UtilityReadingResponseTariff;
  calculation_details?: UtilityReadingResponseCalculationDetails;
  reading_type?: UtilityReadingResponseReadingType;
}
