/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { UtilityTariffUpdateName } from "./utilityTariffUpdateName";
import type { UtilityTariffUpdateRate } from "./utilityTariffUpdateRate";
import type { UtilityTariffUpdateSubscriptionFee } from "./utilityTariffUpdateSubscriptionFee";
import type { UtilityTariffUpdateCurrency } from "./utilityTariffUpdateCurrency";
import type { UtilityTariffUpdateValidFrom } from "./utilityTariffUpdateValidFrom";
import type { UtilityTariffUpdateValidTo } from "./utilityTariffUpdateValidTo";
import type { UtilityTariffUpdateIsActive } from "./utilityTariffUpdateIsActive";

/**
 * Схема для оновлення тарифу
 */
export interface UtilityTariffUpdate {
  name?: UtilityTariffUpdateName;
  rate?: UtilityTariffUpdateRate;
  subscription_fee?: UtilityTariffUpdateSubscriptionFee;
  currency?: UtilityTariffUpdateCurrency;
  valid_from?: UtilityTariffUpdateValidFrom;
  valid_to?: UtilityTariffUpdateValidTo;
  is_active?: UtilityTariffUpdateIsActive;
}
