/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { UtilityReadingUpdatePeriod } from "./utilityReadingUpdatePeriod";
import type { UtilityReadingUpdateCurrentReading } from "./utilityReadingUpdateCurrentReading";
import type { UtilityReadingUpdatePreviousReading } from "./utilityReadingUpdatePreviousReading";
import type { UtilityReadingUpdateTariffId } from "./utilityReadingUpdateTariffId";
import type { UtilityReadingUpdateReadingDate } from "./utilityReadingUpdateReadingDate";
import type { UtilityReadingUpdateIsPaid } from "./utilityReadingUpdateIsPaid";
import type { UtilityReadingUpdateNotes } from "./utilityReadingUpdateNotes";

/**
 * Схема для оновлення показника
 */
export interface UtilityReadingUpdate {
  period?: UtilityReadingUpdatePeriod;
  current_reading?: UtilityReadingUpdateCurrentReading;
  previous_reading?: UtilityReadingUpdatePreviousReading;
  tariff_id?: UtilityReadingUpdateTariffId;
  reading_date?: UtilityReadingUpdateReadingDate;
  is_paid?: UtilityReadingUpdateIsPaid;
  notes?: UtilityReadingUpdateNotes;
}
