/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { UtilityServiceResponseId } from "./utilityServiceResponseId";
import type { UtilityServiceResponseUserId } from "./utilityServiceResponseUserId";
import type { UtilityServiceResponseAddressId } from "./utilityServiceResponseAddressId";
import type { UtilityServiceResponseName } from "./utilityServiceResponseName";
import type { UtilityServiceResponseDescription } from "./utilityServiceResponseDescription";
import type { UtilityServiceResponseUnit } from "./utilityServiceResponseUnit";
import type { UtilityServiceResponseMeterNumber } from "./utilityServiceResponseMeterNumber";
import type { UtilityServiceResponseIsActive } from "./utilityServiceResponseIsActive";
import type { UtilityServiceResponseHasSharedMeter } from "./utilityServiceResponseHasSharedMeter";
import type { UtilityServiceResponseServiceGroup } from "./utilityServiceResponseServiceGroup";
import type { UtilityServiceResponseCreated } from "./utilityServiceResponseCreated";
import type { UtilityServiceResponseUpdated } from "./utilityServiceResponseUpdated";
import type { UtilityServiceResponseAddress } from "./utilityServiceResponseAddress";

/**
 * Схема для відповіді з даними комунальної служби
 */
export interface UtilityServiceResponse {
  id?: UtilityServiceResponseId;
  user_id?: UtilityServiceResponseUserId;
  address_id?: UtilityServiceResponseAddressId;
  name?: UtilityServiceResponseName;
  description?: UtilityServiceResponseDescription;
  unit?: UtilityServiceResponseUnit;
  meter_number?: UtilityServiceResponseMeterNumber;
  is_active?: UtilityServiceResponseIsActive;
  has_shared_meter?: UtilityServiceResponseHasSharedMeter;
  service_group?: UtilityServiceResponseServiceGroup;
  created?: UtilityServiceResponseCreated;
  updated?: UtilityServiceResponseUpdated;
  address?: UtilityServiceResponseAddress;
}
