/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { UtilityAddressResponseId } from "./utilityAddressResponseId";
import type { UtilityAddressResponseUserId } from "./utilityAddressResponseUserId";
import type { UtilityAddressResponseName } from "./utilityAddressResponseName";
import type { UtilityAddressResponseAddress } from "./utilityAddressResponseAddress";
import type { UtilityAddressResponseDescription } from "./utilityAddressResponseDescription";
import type { UtilityAddressResponseIsActive } from "./utilityAddressResponseIsActive";
import type { UtilityAddressResponseSource } from "./utilityAddressResponseSource";
import type { UtilityAddressResponseCreated } from "./utilityAddressResponseCreated";
import type { UtilityAddressResponseUpdated } from "./utilityAddressResponseUpdated";

/**
 * Схема для відповіді з даними адреси комунальних служб
 */
export interface UtilityAddressResponse {
  id?: UtilityAddressResponseId;
  user_id?: UtilityAddressResponseUserId;
  name?: UtilityAddressResponseName;
  address?: UtilityAddressResponseAddress;
  description?: UtilityAddressResponseDescription;
  is_active?: UtilityAddressResponseIsActive;
  source?: UtilityAddressResponseSource;
  created?: UtilityAddressResponseCreated;
  updated?: UtilityAddressResponseUpdated;
}
