/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { UtilityAddressUpdateName } from "./utilityAddressUpdateName";
import type { UtilityAddressUpdateAddress } from "./utilityAddressUpdateAddress";
import type { UtilityAddressUpdateDescription } from "./utilityAddressUpdateDescription";
import type { UtilityAddressUpdateIsActive } from "./utilityAddressUpdateIsActive";
import type { UtilityAddressUpdateSource } from "./utilityAddressUpdateSource";

/**
 * Схема для оновлення адреси комунальних служб
 */
export interface UtilityAddressUpdate {
  name?: UtilityAddressUpdateName;
  address?: UtilityAddressUpdateAddress;
  description?: UtilityAddressUpdateDescription;
  is_active?: UtilityAddressUpdateIsActive;
  source?: UtilityAddressUpdateSource;
}
