/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { UtilityTariffCreateCurrency } from "./utilityTariffCreateCurrency";
import type { UtilityTariffCreateValidTo } from "./utilityTariffCreateValidTo";
import type { UtilityTariffCreateIsActive } from "./utilityTariffCreateIsActive";
import type { UtilityTariffCreateTariffType } from "./utilityTariffCreateTariffType";
import type { UtilityTariffCreateGroupCode } from "./utilityTariffCreateGroupCode";
import type { UtilityTariffCreateCalculationMethod } from "./utilityTariffCreateCalculationMethod";
import type { UtilityTariffCreatePercentageOf } from "./utilityTariffCreatePercentageOf";

/**
 * Схема для створення тарифу
 */
export interface UtilityTariffCreate {
  service_id: number;
  name: string;
  rate: number;
  currency?: UtilityTariffCreateCurrency;
  valid_from: string;
  valid_to?: UtilityTariffCreateValidTo;
  is_active?: UtilityTariffCreateIsActive;
  tariff_type?: UtilityTariffCreateTariffType;
  group_code?: UtilityTariffCreateGroupCode;
  calculation_method?: UtilityTariffCreateCalculationMethod;
  percentage_of?: UtilityTariffCreatePercentageOf;
}
