/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { UtilityReadingCreatePreviousReading } from "./utilityReadingCreatePreviousReading";
import type { UtilityReadingCreateReadingDate } from "./utilityReadingCreateReadingDate";
import type { UtilityReadingCreateIsPaid } from "./utilityReadingCreateIsPaid";
import type { UtilityReadingCreateNotes } from "./utilityReadingCreateNotes";

/**
 * Схема для створення показника
 */
export interface UtilityReadingCreate {
  address_id: number;
  service_id: number;
  period: string;
  current_reading: number;
  previous_reading?: UtilityReadingCreatePreviousReading;
  tariff_id: number;
  reading_date?: UtilityReadingCreateReadingDate;
  is_paid?: UtilityReadingCreateIsPaid;
  notes?: UtilityReadingCreateNotes;
}
