/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import type { UtilityServiceCreateDescription } from "./utilityServiceCreateDescription";
import type { UtilityServiceCreateMeterNumber } from "./utilityServiceCreateMeterNumber";
import type { UtilityServiceCreateIsActive } from "./utilityServiceCreateIsActive";

/**
 * Схема для створення комунальної служби
 */
export interface UtilityServiceCreate {
  address_id: number;
  name: string;
  description?: UtilityServiceCreateDescription;
  unit: string;
  meter_number?: UtilityServiceCreateMeterNumber;
  is_active?: UtilityServiceCreateIsActive;
}
