/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FinMan API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from "@tanstack/vue-query";
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationReturnType,
} from "@tanstack/vue-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import { unref } from "vue";
import type { MaybeRef } from "vue";

import type {
  BodyImportBankStatementApiImportPost,
  HTTPValidationError,
} from ".././model";

/**
 * Універсальний імпорт банківських виписок

Параметри:
    file: Файл з банківськими транзакціями
    mode: Тип банку (wise, p24, revolut, pumb, erste)
    action: Дія - 'show' для попереднього перегляду або 'import' для імпорту даних
 * @summary Import Bank Statement
 */
export const importBankStatementApiImportPost = (
  bodyImportBankStatementApiImportPost: MaybeRef<BodyImportBankStatementApiImportPost>,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<unknown>> => {
  bodyImportBankStatementApiImportPost = unref(
    bodyImportBankStatementApiImportPost
  );
  const formData = new FormData();
  formData.append("file", bodyImportBankStatementApiImportPost.file);
  formData.append("mode", bodyImportBankStatementApiImportPost.mode);
  if (bodyImportBankStatementApiImportPost.action !== undefined) {
    formData.append("action", bodyImportBankStatementApiImportPost.action);
  }

  return axios.post(`/api/import`, formData, options);
};

export const getImportBankStatementApiImportPostMutationOptions = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof importBankStatementApiImportPost>>,
    TError,
    { data: BodyImportBankStatementApiImportPost },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof importBankStatementApiImportPost>>,
  TError,
  { data: BodyImportBankStatementApiImportPost },
  TContext
> => {
  const mutationKey = ["importBankStatementApiImportPost"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof importBankStatementApiImportPost>>,
    { data: BodyImportBankStatementApiImportPost }
  > = (props) => {
    const { data } = props ?? {};

    return importBankStatementApiImportPost(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ImportBankStatementApiImportPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof importBankStatementApiImportPost>>
>;
export type ImportBankStatementApiImportPostMutationBody =
  BodyImportBankStatementApiImportPost;
export type ImportBankStatementApiImportPostMutationError =
  AxiosError<HTTPValidationError>;

/**
 * @summary Import Bank Statement
 */
export const useImportBankStatementApiImportPost = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof importBankStatementApiImportPost>>,
    TError,
    { data: BodyImportBankStatementApiImportPost },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationReturnType<
  Awaited<ReturnType<typeof importBankStatementApiImportPost>>,
  TError,
  { data: BodyImportBankStatementApiImportPost },
  TContext
> => {
  const mutationOptions =
    getImportBankStatementApiImportPostMutationOptions(options);

  return useMutation(mutationOptions);
};
